name: Build Server

on:
  push:
    branches:
      - development
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install
      - run: npm run build
      - name: Package npm bundle
        run: npm pack
      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
      - name: Upload npm package artifact
        uses: actions/upload-artifact@v4
        with:
          name: infected-infected-1.0.0.tgz
          path: infected-infected-1.0.0.tgz
